# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\EMatt\OneDrive - Nova Scotia Community College\w0420789-MatthewsE\Programming\Git Repository\w0420789-MatthewsE\Assignments\Final_Project_GUI\Final_Project_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(862, 754)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEditPopulation = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPopulation.setGeometry(QtCore.QRect(490, 390, 261, 31))
        self.lineEditPopulation.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"")
        self.lineEditPopulation.setObjectName("lineEditPopulation")
        self.listWidgetCountry = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetCountry.setGeometry(QtCore.QRect(30, 50, 341, 621))
        self.listWidgetCountry.setStyleSheet("color: rgb(255, 255, 255);")
        self.listWidgetCountry.setObjectName("listWidgetCountry")
        self.labelPopulation = QtWidgets.QLabel(self.centralwidget)
        self.labelPopulation.setGeometry(QtCore.QRect(410, 389, 81, 31))
        self.labelPopulation.setAutoFillBackground(False)
        self.labelPopulation.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelPopulation.setObjectName("labelPopulation")
        self.pushButtonUpdatePopulation = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonUpdatePopulation.setGeometry(QtCore.QRect(610, 440, 141, 31))
        self.pushButtonUpdatePopulation.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButtonUpdatePopulation.setObjectName("pushButtonUpdatePopulation")
        self.labelTotalArea = QtWidgets.QLabel(self.centralwidget)
        self.labelTotalArea.setGeometry(QtCore.QRect(410, 500, 80, 31))
        self.labelTotalArea.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelTotalArea.setObjectName("labelTotalArea")
        self.groupBoxPopulationDensity = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxPopulationDensity.setGeometry(QtCore.QRect(410, 550, 341, 71))
        self.groupBoxPopulationDensity.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBoxPopulationDensity.setObjectName("groupBoxPopulationDensity")
        self.radioButtonSquareMile = QtWidgets.QRadioButton(self.groupBoxPopulationDensity)
        self.radioButtonSquareMile.setGeometry(QtCore.QRect(10, 20, 131, 17))
        self.radioButtonSquareMile.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButtonSquareMile.setObjectName("radioButtonSquareMile")
        self.radioButtonSquareKM = QtWidgets.QRadioButton(self.groupBoxPopulationDensity)
        self.radioButtonSquareKM.setGeometry(QtCore.QRect(10, 40, 131, 17))
        self.radioButtonSquareKM.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButtonSquareKM.setObjectName("radioButtonSquareKM")
        self.labelSquareAreaDisplay = QtWidgets.QLabel(self.groupBoxPopulationDensity)
        self.labelSquareAreaDisplay.setGeometry(QtCore.QRect(220, 25, 101, 30))
        self.labelSquareAreaDisplay.setText("")
        self.labelSquareAreaDisplay.setObjectName("labelSquareAreaDisplay")
        self.labelPercentPop = QtWidgets.QLabel(self.centralwidget)
        self.labelPercentPop.setGeometry(QtCore.QRect(410, 645, 161, 21))
        self.labelPercentPop.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelPercentPop.setObjectName("labelPercentPop")
        self.labelPercentPopDisplay = QtWidgets.QLabel(self.centralwidget)
        self.labelPercentPopDisplay.setGeometry(QtCore.QRect(630, 644, 111, 21))
        self.labelPercentPopDisplay.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelPercentPopDisplay.setText("")
        self.labelPercentPopDisplay.setObjectName("labelPercentPopDisplay")
        self.labelCountryListTitle = QtWidgets.QLabel(self.centralwidget)
        self.labelCountryListTitle.setGeometry(QtCore.QRect(30, 20, 331, 21))
        self.labelCountryListTitle.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelCountryListTitle.setObjectName("labelCountryListTitle")
        self.labelVarCountryName = QtWidgets.QLabel(self.centralwidget)
        self.labelVarCountryName.setGeometry(QtCore.QRect(400, 35, 111, 31))
        self.labelVarCountryName.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelVarCountryName.setText("")
        self.labelVarCountryName.setObjectName("labelVarCountryName")
        self.labelVarTotalAreaIn = QtWidgets.QLabel(self.centralwidget)
        self.labelVarTotalAreaIn.setGeometry(QtCore.QRect(620, 500, 111, 31))
        self.labelVarTotalAreaIn.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelVarTotalAreaIn.setText("")
        self.labelVarTotalAreaIn.setObjectName("labelVarTotalAreaIn")
        self.verticalScrollBarCountryLists = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBarCountryLists.setGeometry(QtCore.QRect(350, 50, 21, 621))
        self.verticalScrollBarCountryLists.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBarCountryLists.setObjectName("verticalScrollBarCountryLists")
        self.comboBoxMilesToKM = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxMilesToKM.setGeometry(QtCore.QRect(490, 506, 69, 20))
        self.comboBoxMilesToKM.setObjectName("comboBoxMilesToKM")
        self.labelcheckBoxToggleImage = QtWidgets.QLabel(self.centralwidget)
        self.labelcheckBoxToggleImage.setGeometry(QtCore.QRect(510, 130, 191, 181))
        self.labelcheckBoxToggleImage.setObjectName("labelcheckBoxToggleImage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 862, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_File = QtWidgets.QAction(MainWindow)
        self.actionLoad_File.setObjectName("actionLoad_File")
        self.actionSave_File = QtWidgets.QAction(MainWindow)
        self.actionSave_File.setObjectName("actionSave_File")
        self.menuFile.addAction(self.actionLoad_File)
        self.menuFile.addAction(self.actionSave_File)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelPopulation.setText(_translate("MainWindow", " Population:"))
        self.pushButtonUpdatePopulation.setText(_translate("MainWindow", "Update Population"))
        self.labelTotalArea.setText(_translate("MainWindow", "Total Area in:"))
        self.groupBoxPopulationDensity.setTitle(_translate("MainWindow", "Population Density"))
        self.radioButtonSquareMile.setText(_translate("MainWindow", "Per Square Mile"))
        self.radioButtonSquareKM.setText(_translate("MainWindow", "Per Sqaure KM"))
        self.labelPercentPop.setText(_translate("MainWindow", "Percentage of World Population:"))
        self.labelCountryListTitle.setText(_translate("MainWindow", "Choose A Country From the List:"))
        self.labelcheckBoxToggleImage.setText(_translate("MainWindow", "TextLabel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_File.setText(_translate("MainWindow", "Load File"))
        self.actionSave_File.setText(_translate("MainWindow", "Save File"))

import newprefex_rc
