# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\EMatt\OneDrive - Nova Scotia Community College\w0420789-MatthewsE\Programming\Git Repository\w0420789-MatthewsE\Assignments\Final_Project_Ethan_Matthews\Final_Project.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow") 
        MainWindow.resize(800, 745)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEditPopulation = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPopulation.setGeometry(QtCore.QRect(480, 400, 261, 31))
        self.lineEditPopulation.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"")
        self.lineEditPopulation.setObjectName("lineEditPopulation")
        self.comboBoxMilesToKM = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxMilesToKM.setGeometry(QtCore.QRect(480, 516, 69, 20))
        self.comboBoxMilesToKM.setObjectName("comboBoxMilesToKM")
        self.labelCountryListTitle = QtWidgets.QLabel(self.centralwidget)
        self.labelCountryListTitle.setGeometry(QtCore.QRect(20, 30, 331, 21))
        self.labelCountryListTitle.setObjectName("labelCountryListTitle")
        self.labelVarTotalAreaIn = QtWidgets.QLabel(self.centralwidget)
        self.labelVarTotalAreaIn.setGeometry(QtCore.QRect(610, 510, 111, 31))
        self.labelVarTotalAreaIn.setText("")
        self.labelVarTotalAreaIn.setObjectName("labelVarTotalAreaIn")
        self.groupBoxPopulationDensity = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxPopulationDensity.setGeometry(QtCore.QRect(400, 560, 341, 71))
        self.groupBoxPopulationDensity.setObjectName("groupBoxPopulationDensity")
        self.radioButtonSquareMile = QtWidgets.QRadioButton(self.groupBoxPopulationDensity)
        self.radioButtonSquareMile.setGeometry(QtCore.QRect(10, 20, 131, 17))
        self.radioButtonSquareMile.setStyleSheet("color: rgb(0, 0, 0);")
        self.radioButtonSquareMile.setObjectName("radioButtonSquareMile")
        self.radioButtonSquareKM = QtWidgets.QRadioButton(self.groupBoxPopulationDensity)
        self.radioButtonSquareKM.setGeometry(QtCore.QRect(10, 40, 131, 17))
        self.radioButtonSquareKM.setStyleSheet("color: rgb(0, 0, 0);")
        self.radioButtonSquareKM.setObjectName("radioButtonSquareKM")
        self.labelSquareAreaDisplay = QtWidgets.QLabel(self.groupBoxPopulationDensity)
        self.labelSquareAreaDisplay.setGeometry(QtCore.QRect(220, 25, 101, 30))
        self.labelSquareAreaDisplay.setText("")
        self.labelSquareAreaDisplay.setObjectName("labelSquareAreaDisplay")
        self.labelFlagImage = QtWidgets.QLabel(self.centralwidget)
        self.labelFlagImage.setGeometry(QtCore.QRect(450, 120, 241, 201))
        self.labelFlagImage.setText("")
        self.labelFlagImage.setObjectName("labelFlagImage")
        self.labelPercentPopDisplay = QtWidgets.QLabel(self.centralwidget)
        self.labelPercentPopDisplay.setGeometry(QtCore.QRect(620, 654, 111, 21))
        self.labelPercentPopDisplay.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelPercentPopDisplay.setText("")
        self.labelPercentPopDisplay.setObjectName("labelPercentPopDisplay")
        self.pushButtonUpdatePopulation = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonUpdatePopulation.setGeometry(QtCore.QRect(600, 450, 141, 31))
        self.pushButtonUpdatePopulation.setObjectName("pushButtonUpdatePopulation")
        self.verticalScrollBarCountryLists = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBarCountryLists.setGeometry(QtCore.QRect(340, 60, 21, 621))
        self.verticalScrollBarCountryLists.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBarCountryLists.setObjectName("verticalScrollBarCountryLists")
        self.labelPopulation = QtWidgets.QLabel(self.centralwidget)
        self.labelPopulation.setGeometry(QtCore.QRect(400, 399, 81, 31))
        self.labelPopulation.setAutoFillBackground(False)
        self.labelPopulation.setStyleSheet("")
        self.labelPopulation.setObjectName("labelPopulation")
        self.labelTotalArea = QtWidgets.QLabel(self.centralwidget)
        self.labelTotalArea.setGeometry(QtCore.QRect(400, 510, 80, 31))
        self.labelTotalArea.setObjectName("labelTotalArea")
        self.listWidgetCountry = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetCountry.setGeometry(QtCore.QRect(20, 60, 341, 621))
        self.listWidgetCountry.setObjectName("listWidgetCountry")
        self.labelVarCountryName = QtWidgets.QLabel(self.centralwidget)
        self.labelVarCountryName.setGeometry(QtCore.QRect(390, 45, 111, 31))
        self.labelVarCountryName.setText("")
        self.labelVarCountryName.setObjectName("labelVarCountryName")
        self.labelPercentPop = QtWidgets.QLabel(self.centralwidget)
        self.labelPercentPop.setGeometry(QtCore.QRect(400, 655, 161, 21))
        self.labelPercentPop.setObjectName("labelPercentPop")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuFiel = QtWidgets.QMenu(self.menubar)
        self.menuFiel.setObjectName("menuFiel")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_File = QtWidgets.QAction(MainWindow)
        self.actionLoad_File.setObjectName("actionLoad_File")
        self.actionSave_File = QtWidgets.QAction(MainWindow)
        self.actionSave_File.setObjectName("actionSave_File")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFiel.addAction(self.actionLoad_File)
        self.menuFiel.addAction(self.actionSave_File)
        self.menuFiel.addAction(self.actionExit)
        self.menubar.addAction(self.menuFiel.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelCountryListTitle.setText(_translate("MainWindow", "Choose A Country From the List:"))
        self.groupBoxPopulationDensity.setTitle(_translate("MainWindow", "Population Density"))
        self.radioButtonSquareMile.setText(_translate("MainWindow", "Per Square Mile"))
        self.radioButtonSquareKM.setText(_translate("MainWindow", "Per Sqaure KM"))
        self.pushButtonUpdatePopulation.setText(_translate("MainWindow", "Update Population"))
        self.labelPopulation.setText(_translate("MainWindow", " Population:"))
        self.labelTotalArea.setText(_translate("MainWindow", "Total Area in:"))
        self.labelPercentPop.setText(_translate("MainWindow", "Percentage of World Population:"))
        self.menuFiel.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_File.setText(_translate("MainWindow", "Load File"))
        self.actionSave_File.setText(_translate("MainWindow", "Save File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

